# Generated by Django 6.0 on 2025-12-14 22:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do hábito (Ex: Fazer exercícios físicos)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição do hábito', max_length=500)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1, help_text='Quantidade de vezes que o hábito deve ser realizado')),
                ('color', models.CharField(choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#F59E0B', 'Amarelo'), ('#EF4444', 'Vermelho'), ('#8B5CF6', 'Roxo'), ('#EC4899', 'Rosa')], default='#3B82F6', help_text='Cor do hábito', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Hábito ativo')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data em que o hábito foi realizado')),
                ('done', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], help_text='Avaliação de 1 a 5 estrelas para o check-in', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observações sobre o check-in', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='api.habit')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_habit_name'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_checkin_per_day'),
        ),
    ]
